export const FIREBASE_ERRORS = {
    'Firebase: Error (auth/email-already-in-use).': 'Email already in use',
    'Firebase: Error (auth/invalid-email).': 'Invalid email',
    'Firebase: Error (auth/user-not-found).': 'Wrong email or password',
    'Firebase: Error (auth/wrong-password).': 'Wrong email or password',
    'Firebase: Error (auth/weak-password).': 'Weak password',
    'Firebase: Error (auth/invalid-verification-code).': 'Invalid verification code',
    'Firebase: Error (auth/invalid-verification-id).': 'Invalid verification id',
    'Firebase: Error (auth/requires-recent-login).': 'Requires recent login',
    'Firebase: Error (auth/user-disabled).': 'User disabled',
    'Firebase: Error (auth/user-token-expired).': 'User token expired',
    'Firebase: Error (auth/invalid-user-token).': 'Invalid user token',
    'Firebase: Error (auth/network-request-failed).': 'Network request failed',
    'Firebase: Error (auth/too-many-requests).': 'Too many requests',
    'Firebase: Error (auth/operation-not-allowed).': 'Operation not allowed',
    'Firebase: Error (auth/internal-error).': 'Internal error',
    'Firebase: Error (auth/invalid-credential).': 'Invalid credential',
    'Firebase: Error (auth/account-exists-with-different-credential).': 'Account exists with different credential',
    'Firebase: Error (auth/credential-already-in-use).': 'Credential already in use',
    'Firebase: Error (auth/user-mismatch).': 'User mismatch',
    'Firebase: Error (auth/provider-already-linked).': 'Provider already linked',
    'Firebase: Error (auth/no-such-provider).': 'No such provider',
    'Firebase: Error (auth/missing-android-pkg-name).': 'Missing android package name',
    'Firebase: Error (auth/missing-continue-uri).': 'Missing continue uri',
    'Firebase: Error (auth/missing-ios-bundle-id).': 'Missing ios bundle id',
    'Firebase: Error (auth/invalid-continue-uri).': 'Invalid continue uri',
    'Firebase: Error (auth/unauthorized-continue-uri).': 'Unauthorized continue uri',
    'Firebase: Error (auth/invalid-dynamic-link-domain).': 'Invalid dynamic link domain',
    'Firebase: Error (auth/argument-error).': 'Argument error',
};