import Header from "@/components/Header";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Footer from "@/components/Footer";
import Login from "@/components/Login";
import { Providers } from "./providers";
import UserDashboard from "@/components/UserDashboard";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          <div className="flex-main-col brand-bg">
            <Header />
            <Login />
            <UserDashboard />
            <main className="flex-1-col p-4">{children}</main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
