import Header from "@/components/Header";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Footer from "@/components/Footer";
import Login from "@/components/Login";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="flex-main-col brand-bg">
          <Header />
          <Login />
          <main className="flex-1-col p-4">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
